language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- curl https://commbank.artifactoryonline.com/commbank/binaries/ci/ci-3.3.0-20160817231550-75d3c9c.tar.gz | tar xz
- ci/sbt-ci-setup.sh
- ci/sbt-ci-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package'
  && ci/sbt-ci-deploy.sh maven http://commbank.artifactoryonline.com/commbank ext-releases-local
  && ci/sbt-ci-build-doc.sh https://commbank.github.io/ https://github.com/CommBank/beeswax/
  && ci/ci-push-branch.sh gh-pages
after_script:
- rm -rf ci
env:
  global:
  - secure: IGmjQG1otLG8HU87jN4dfXO3LI/mrGgRijNoybOzsZXadybpxd3cp2gN/unduKkqJqxUtT2ZIEAAnOkz1vbhlAAamY0xNKn9N0eGmM+CDad1kOOhdqItVDUkMiCbQyFxhdJbjHD7wc8Rj2JfZmXfMJakAxquGbaZGVPAM34TzyQHayFz61DKWy5YxntctPEIfdljLU4AI+BeYVS90CAvIVye3v/kf1+Zma10tkegPDx//LTksHrgEs3NCWTUqK784x1HvCNd8rZrWoWlP204NKp/4VRs/4U8h8D2iLnvr1i5vEulczmB53ouy3wbDNnHxoA1K2GfQGz7jZW9EeLxUP2POrDQftpCvDO64h7MZ+yxzfM8is2uSjcaxUh/K6XKhaiKsImOepbPNFbr5u/y52u7hMRmUu0wKu/i9vCCF/r7u+NLwFG1n+whE/g49mgKg9QHqEHA9sbdEISMsE7e10Xy9THMCe3vbzk5kPKhofg1pHdiKHbNN4j4evuVTMBRl3TeriJgBYeycLVOzUygOI0yT+cA57581Bz8cEUY91cw08qJZkVPxV9DQiedCp7LLi+kXwQRUiI8JoHN/v9/pGd10h1P127AmIqkGYSB1+MgKte3p+Sco6gVx7ynUyylM628cwP59roZ9s6VS2ZeORxO4V+9cUm/9KpX9j9xrLw=
  - secure: ABdBWp0VMJzWLrj9pD+BHdP+5gpppaj7Sl178iVAz143PLXNMHJEzO1qqTY07/X/dUC5IBXuZrjbU221LXOYc2bqRUsWP/l+cH6ZUyP0Cyaxr7raJZFLG4Cfz0z9/bXk1Ssgu1l6EqlkkLXL9jYV3I2ZW0QHDF5q0v2uMLQRS5OsQvWrdL8GI39ut4l8yXXWjKERbR0qXoRjQTQsvN+9I3xg7+yvDTGBvWDJ8a/4WxhS3g+Csfpqc/FU/VXO3XX1NzkC44vegxxHwKOleH9TaQAjvkBvs+NLcJErYVx1qytPaYChYcWWVHLim+I9aXPU2er+PvFCBQvre+OwrPUylUZ8NrM3CuVopuiCcp9yD0r/W0dwui71HbqEHoRvbjCA8nvqRULLDqJhGDhk8r30ohoTdOLC1XbF9Xjc4zb3q8lAGR2s/fgQfgfUiEk8kIpKMsqwMxCS93uwCh+P63j2268T1WwRrpr/vqVk89/2PqnRf4NgtNgVGE6tp5OywWB2zUpNOiIjE6jIFwhZkZ/pltyXB9nXM7BJ+GsC00ZaKjpKI/rB1zPZ59WKjlUhP6g2kOng8axCFLo7Go0mWy/o5Hg6zQYQ7vrX2SSKzVUy3vMTTmoIftdvqQX6iCR7/Lymos7+Lj729Q+7QzjKCsEgvW9Tue5XWqfEGzh7qEcGCsY=
before_install:
- openssl aes-256-cbc -K $encrypted_d84550f15e95_key -iv $encrypted_d84550f15e95_iv
  -in .ci/deploy-key.enc -out .ci/deploy-key.pem -d
